export default function(key:any){
    switch(key){
        case 203 : return 'Protein';
        case 204 : return 'Fat';
        case 205 : return 'Carbohydrate';
        case 207 : return 'ASH';
        case 208 : return 'Energy';
        case 209 : return 'Starch';
        case 210 : return 'Sucrose';
        case 211 : return 'Glucose';
        case 212 : return 'Fructose';
        case 213 : return 'Lactose';
        case 214 : return 'Maltose';
        case 221 : return 'Alcohol';
        case 255 : return 'Water';
        case 257 : return 'Adjusted Protein';
        case 262 : return 'Caffeine';
        case 263 : return 'Theobromine';
        case 268 : return 'Energy';
        case 269 : return 'Sugars';
        case 287 : return 'Galactose';
        case 291 : return 'Fiber, total dietary';
        case 301 : return 'Calcium';
        case 303 : return 'Iron';
        case 304 : return 'Magnesium';
        case 305 : return 'Phosphorus';
        case 306 : return 'Potassium';
        case 307 : return 'Sodium';
        case 309 : return 'Zinc';
        case 312 : return 'Copper';
        case 313 : return 'Fluoride';
        case 315 : return 'Manganese';
        case 317 : return 'Selenium';
        case 318 : return 'Vitamin A';
        case 319 : return 'Retinol';
        case 321 : return 'Carotene, beta';
        case 322 : return 'Carotene, alpha';
        case 323 : return 'Vitamin E';
        case 324 : return 'Vitamin D';
        case 325 : return 'Vitamin D2';
        case 326 : return 'Vitamin D3';
        case 334 : return 'Cryptoxanthin';
        case 337 : return 'Lycopene';
        case 338 : return 'Lutein + zeaxanthin';
        case 341 : return 'Tocopherol, beta';
        case 342 : return 'Tocopherol, gamma';
        case 343 : return 'Tocopherol, delta';
        case 344 : return 'Tocotrienol, alpha';
        case 345 : return 'Tocotrienol, beta';
        case 346 : return 'Tocotrienol, gamma';
        case 347 : return 'Tocotrienol,delta';
        case 401 : return 'itamin C, total ascorbic acid';
        case 404 : return 'Thiamin';
        case 405 : return 'Riboflavin';
        case 406 : return 'Niacin';
        case 410 : return 'Pantothenic acid';
        case 415 : return 'Vitamin B-6';
        case 417 : return 'Folate';
        case 418 : return 'Vitamin B-12';
        case 421 : return 'Choline';
        case 428 : return 'Menaquinone';
        case 429 : return 'Dihydrophylloquinone';
        case 430 : return 'Vitamin K';
        case 431 : return 'Folic acid';
        case 454 : return 'Betaine';
        case 501 : return 'Tryptophan';
        case 502 : return 'Threonine';
        case 503 : return 'Isoleucine';
        case 504 : return 'Leucine';
        case 505 : return 'Lysine';
        case 506 : return 'Methionine';
        case 507 : return 'Cystine';
        case 508 : return 'Phenylalanine';
        case 509 : return 'Tyrosine';
        case 510 : return 'Valine';
        case 511 : return 'Arginine';
        case 512 : return 'Histidine';
        case 513 : return 'Alanine';
        case 514 : return 'Aspartic acid';
        case 515 : return 'Glutamic acid';
        case 516 : return 'Glycine';
        case 517 : return 'Proline';
        case 518 : return 'Serine';
        case 521 : return 'Hydroxyproline';
        case 573 : return 'Vitamin E';
        case 578 : return 'Vitamin B-12';
        case 601 : return 'Cholesterol';
        default : return 'Unknown';
    }

}